Repository ezsystems/ezplatform-graphql, pull requests merged in 2019-03, with the labels that each got.

#16 EZP-30325: Generated schema is not being used when vendor packages are symlinked
  src/DependencyInjection/Compiler/FieldValueTypesPass.php
  src/DependencyInjection/Compiler/RegisterSchemaDirectoryParametersPass.php
  src/DependencyInjection/EzSystemsEzPlatformGraphQLExtension.php
  src/EzSystemsEzPlatformGraphQLBundle.php
Labels: bug

#11 EZP-30283: Implement fetching Object States in GraphQL
  src/GraphQL/Resolver/ObjectStateGroupResolver.php
  src/GraphQL/Resolver/ObjectStateResolver.php
  src/Resources/config/graphql/Content.types.yml
  src/Resources/config/graphql/ObjectState.types.yml
  src/Resources/config/graphql/ObjectStateGroup.types.yml
  src/Resources/config/graphql/Repository.types.yml
  src/Resources/config/resolvers.yml
Labels: enhancement

#3 Use a Cached ContentLoader in DomainContentResolver
  spec/EzSystems/EzPlatformGraphQL/GraphQL/Resolver/DomainContentResolverSpec.php
  src/DependencyInjection/EzSystemsEzPlatformGraphQLExtension.php
  src/GraphQL/DataLoader/CachedContentLoader.php
  src/GraphQL/DataLoader/CachedContentTypeLoader.php
  src/GraphQL/DataLoader/ContentLoader.php
  src/GraphQL/DataLoader/ContentTypeLoader.php
  src/GraphQL/DataLoader/Exception/NotFoundException.php
  src/GraphQL/DataLoader/RepositoryContentTypeLoader.php
  src/GraphQL/DataLoader/SearchContentLoader.php
  src/GraphQL/Resolver/ContentResolver.php
  src/GraphQL/Resolver/DomainContentResolver.php
  src/GraphQL/Resolver/ImageAssetFieldResolver.php
  src/GraphQL/Resolver/ImageFieldResolver.php
  src/GraphQL/Resolver/SearchResolver.php
  src/GraphQL/Resolver/SelectionFieldResolver.php
  src/Resources/config/graphql/DomainContent.types.yml
  src/Resources/config/resolvers.yml
  src/Resources/config/services/data_loaders.yml
Labels: performances
