Repository ezsystems/ezplatform-graphql, pull requests merged in 2019-12, with the labels that each got.

#71 EZP-31108: Provided common PHP CS Fixer configuration for internal use
  .php_cs
  composer.json
  src/DependencyInjection/Compiler/FieldInputHandlersPass.php
  src/DependencyInjection/Compiler/InputTypesMappingPass.php
  src/DependencyInjection/Compiler/RichTextInputConvertersPass.php
  src/DependencyInjection/EzSystemsEzPlatformGraphQLExtension.php
  src/GraphQL/DataLoader/CachedContentLoader.php
  src/GraphQL/DataLoader/ContentLoader.php
  src/GraphQL/DataLoader/LocationLoader.php
  src/GraphQL/DataLoader/SearchContentLoader.php
  src/GraphQL/DataLoader/SearchLocationLoader.php
  src/GraphQL/InputMapper/SearchQueryMapper.php
  src/GraphQL/Mutation/UploadFiles.php
  src/GraphQL/Relay/NodeResolver.php
  src/GraphQL/Resolver/ContentThumbnailResolver.php
  src/GraphQL/Resolver/DomainContentResolver.php
  src/GraphQL/Resolver/ImageAssetFieldResolver.php
  src/GraphQL/Resolver/ImageFieldResolver.php
  src/GraphQL/Resolver/LocationResolver.php
  src/GraphQL/Resolver/ObjectStateGroupResolver.php
  src/GraphQL/Resolver/ObjectStateResolver.php
  src/GraphQL/Resolver/SearchResolver.php
  src/GraphQL/Resolver/SelectionFieldResolver.php
  src/Schema/Builder.php
  src/Schema/Builder/SchemaBuilder.php
  src/Schema/Domain/Content/ContentDomainIterator.php
  src/Schema/Domain/Content/LanguagesIterator.php
  src/Schema/Domain/Content/Mapper/FieldDefinition/RelationFieldDefinitionMapper.php
  src/Schema/Domain/Content/NameHelper.php
  src/Schema/Domain/Content/Worker/ContentType/AddContentOfTypeConnectionToDomainGroup.php
  src/Schema/Domain/Content/Worker/ContentType/AddContentTypeToContentTypeIdentifierList.php
  src/Schema/Domain/Content/Worker/ContentType/AddContentTypeToDomainGroupTypes.php
  src/Schema/Domain/Content/Worker/ContentType/AddDomainContentToDomainGroup.php
  src/Schema/Domain/Content/Worker/ContentType/DefineDomainContent.php
  src/Schema/Domain/Content/Worker/ContentType/DefineDomainContentConnection.php
  src/Schema/Domain/Content/Worker/ContentType/DefineDomainContentMutation.php
  src/Schema/Domain/Content/Worker/ContentType/DefineDomainContentType.php
  src/Schema/Domain/Content/Worker/ContentTypeGroup/AddDomainGroupToDomain.php
  src/Schema/Domain/Content/Worker/ContentTypeGroup/DefineDomainGroup.php
  src/Schema/Domain/Content/Worker/ContentTypeGroup/DefineDomainGroupTypes.php
  src/Schema/Domain/Content/Worker/FieldDefinition/AddFieldDefinitionToDomainContentMutation.php
  src/Schema/Domain/Content/Worker/FieldDefinition/AddFieldDefinitionToDomainContentType.php
  src/Schema/Domain/Content/Worker/FieldDefinition/AddFieldValueToDomainContent.php
  src/Schema/Domain/Content/Worker/Language/AddLanguageToEnum.php
  src/Schema/Domain/Iterator.php
  src/Schema/Worker.php
Labels: Improvement, Ready for review

#70 EZP-31021: Revise exception & command microcopy
  src/GraphQL/Mutation/UploadFiles.php
  src/GraphQL/Resolver/ContentThumbnailResolver.php
  src/GraphQL/Resolver/DomainContentMutationResolver.php
  src/GraphQL/Resolver/ImageFieldResolver.php
  src/GraphQL/Resolver/ObjectStateGroupResolver.php
  src/GraphQL/Resolver/ObjectStateResolver.php
  src/Schema/Domain/Content/Worker/ContentType/AddContentOfTypeConnectionToDomainGroup.php
  src/Schema/Domain/Content/Worker/ContentType/AddDomainContentToDomainGroup.php
Labels: Ready for MERGE

#72 EZP-31240: Querying for contentobjects missing ImageAsset FieldType in GraphQL ends up with an error
  src/GraphQL/Resolver/ImageAssetFieldResolver.php
Labels: Bug, QA approved, Ready for MERGE
