Repository ezsystems/ezplatform-graphql, pull requests merged in 2021-12, with the labels that each got.

#114 IBX-1520: Fixed loading sub-items on PHP8
  composer.json
Labels: Bug, QA approved

#118 IBX-1604: Fixed deprecation warning related to PHP8 (#11)
  src/GraphQL/InputMapper/SearchQueryMapper.php
Labels: Ready for review

#116 IBX-1565: Refactor schema's types' names validation
  spec/EzSystems/EzPlatformGraphQL/Schema/Builder/SchemaBuilderSpec.php
  spec/EzSystems/EzPlatformGraphQL/Schema/Domain/Content/ContentDomainIteratorSpec.php
  src/Resources/config/services/schema.yml
  src/Schema/Builder/SchemaBuilder.php
  src/Schema/Domain/Content/ContentDomainIterator.php
  src/Schema/Domain/ImageVariationDomain.php
Labels: Bug, QA approved, Ready for MERGE
